project:
  type: website
  output-dir: docs

website:
  title: "Flavio Matos"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: portfolio.qmd
        text: Portfolio
      - href: talks.qmd
        text: Talks
      - href: blog.qmd
        text: Blog
      - href: contact.qmd
        text: Contact
  back-to-top-navigation: true
  open-graph:
    locale: en_GB
  google-analytics:
    tracking-id: "G-Y63K6B8EJ2"
    anonymize-ip: true
  cookie-consent:
    type: express
    prefs-text: "Cookie Preferences"
    
        
  page-footer:
    border: true
    left: "© 2026 Flavio Matos · Made with [Quarto](https://quarto.org/){target=_blank}"
    center:
      - icon: linkedin
        href: https://www.linkedin.com/in/flavio-matos/
        target: _blank
      - icon: github
        href: https://github.com/MatosFlavio
        target: _blank
      - icon: envelope
        href: mailto:flavio.matos@faktaconsulting.com
        target: _blank
      - icon: palette
        href: https://public.tableau.com/app/profile/flavio.matos/vizzes
        target: _blank
      - icon: newspaper
        href: https://flaviomatos.substack.com
        target: _blank
    right: 
      - text: License
        href: license.qmd
      - text: Contact
        href: contact.qmd


format:
  html:
    theme: 
      light: [assets/theme_light.scss, flatly]
      dark: [assets/theme_dark.scss]
    toc: true
    page-layout: article
    
comments:
  giscus:
    repo: MatosFlavio/matosflavio-website-giscus
